version: 2.1

jobs:
  test:
    docker:
      - image: pbxx/dev-env:main-latest
        auth:
          username: $DOCKER_LOGIN
          password: $DOCKER_PASSWORD
    working_directory: /go/src/github.com/promoboxx/go-client
    steps:
      - checkout
      - run:
          name: go test
          command: go test -mod vendor -v -cover -run Unit ./client/...
workflows:
  version: 2
  test:
    jobs:
      - test:
          context: "dockerhub"
          filters:
            branches:
              ignore: master
