version: 2.1
jobs:
  test:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/promoboxx/go-client
    steps:
      - checkout
      - run:
          name: golint
          command: |
            go get -u golang.org/x/lint/golint
            golint ./src/...
      - run:
          name: go vet
          command: go vet ./src/...
      - run:
          name: gofmt
          command: test -z "$(gofmt -s -l src)"
      - run:
          name: go test
          command: go test -v -cover -run Unit ./...  
workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            branches:
              ignore: master
      