// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/promoboxx/go-client/client (interfaces: BaseClient)

// Package clientmock is a generated GoMock package.
package clientmock

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	glitch "github.com/promoboxx/go-glitch/glitch"
	io "io"
	http "net/http"
	url "net/url"
	reflect "reflect"
)

// MockBaseClient is a mock of BaseClient interface
type MockBaseClient struct {
	ctrl     *gomock.Controller
	recorder *MockBaseClientMockRecorder
}

// MockBaseClientMockRecorder is the mock recorder for MockBaseClient
type MockBaseClientMockRecorder struct {
	mock *MockBaseClient
}

// NewMockBaseClient creates a new mock instance
func NewMockBaseClient(ctrl *gomock.Controller) *MockBaseClient {
	mock := &MockBaseClient{ctrl: ctrl}
	mock.recorder = &MockBaseClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockBaseClient) EXPECT() *MockBaseClientMockRecorder {
	return m.recorder
}

// Do mocks base method
func (m *MockBaseClient) Do(arg0 context.Context, arg1, arg2 string, arg3 url.Values, arg4 http.Header, arg5 io.Reader, arg6 interface{}) glitch.DataError {
	ret := m.ctrl.Call(m, "Do", arg0, arg1, arg2, arg3, arg4, arg5, arg6)
	ret0, _ := ret[0].(glitch.DataError)
	return ret0
}

// Do indicates an expected call of Do
func (mr *MockBaseClientMockRecorder) Do(arg0, arg1, arg2, arg3, arg4, arg5, arg6 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockBaseClient)(nil).Do), arg0, arg1, arg2, arg3, arg4, arg5, arg6)
}

// MakeRequest mocks base method
func (m *MockBaseClient) MakeRequest(arg0 context.Context, arg1, arg2 string, arg3 url.Values, arg4 http.Header, arg5 io.Reader) (int, []byte, glitch.DataError) {
	ret := m.ctrl.Call(m, "MakeRequest", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(glitch.DataError)
	return ret0, ret1, ret2
}

// MakeRequest indicates an expected call of MakeRequest
func (mr *MockBaseClientMockRecorder) MakeRequest(arg0, arg1, arg2, arg3, arg4, arg5 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeRequest", reflect.TypeOf((*MockBaseClient)(nil).MakeRequest), arg0, arg1, arg2, arg3, arg4, arg5)
}
